header_links:
  default: >-
    [
      {"linkText":"Forum","url":"/"}
    ]
  json_schema: '{
    "type": "array",
    "format": "table",
    "uniqueItems": true,
    "items": {
      "type": "object",
      "properties": {
        "linkText": {
         "type": "string",
          "minLength": 1
        },
        "url": {
          "type": "string"
        },
        "submenu": {
          "type": "string"
        }
      },
      "additionalProperties": false
    }
  }'

links_position:
  default: right
  type: enum
  choices:
    - right
    - left
  description:
    en: "Note that when links are displayed on the left, they're automatically hidden while scrolling within topics to make room for the title"

brand_name:
  default: "The Puttyverse"
byline:
  default: "Support + Inspiration for Multipotentialites"
website_url:
  default: "https://theputtyverse.com/"
forum_url:
  default: "https://forum.theputtyverse.com/"
logo_url:
  default: "https://theputtyverseprod.b-cdn.net/original/2X/8/8e93f3759d4c9afe00564cc9182ade6d699f46c5.png"
dark_logo_url:
  default: "https://theputtyverseprod.b-cdn.net/original/3X/b/e/bebcd68303bb82ba019699aaf0cee1d7869959fa.png"
mobile_logo_url:
  default: "https://theputtyverseprod.b-cdn.net/original/2X/2/2ea60de30341a27c8b57cb8a6507757b8d3d2fd2.png"
links:
  type: list
  list_type: simple
  default: ""
  description: "Format: name,url,target (optional)"
